# Generated by Django 5.1.1 on 2024-10-08 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_library'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
